version: "3.7"
services:


  node:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

    environment:
      - PORT=3000
    volumes:
      - ./services:/services
      - /services/node_modules
